// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzCsX1bbSX4KCBeERTzzQtLiMkAmkm9dQ',
    appId: '1:157134124123:web:ba0faaa991902cc4aefb7e',
    messagingSenderId: '157134124123',
    projectId: 'myinvoicemate',
    authDomain: 'myinvoicemate.firebaseapp.com',
    storageBucket: 'myinvoicemate.firebasestorage.app',
    measurementId: 'G-JQMRCCBP9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5WY2Y2HUX-25mkTTRUXwmNPw2WQAfZL8',
    appId: '1:157134124123:android:1aea4d16aedad35aaefb7e',
    messagingSenderId: '157134124123',
    projectId: 'myinvoicemate',
    storageBucket: 'myinvoicemate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0IJ5B5tOuFpj2RmxyRtbaGDHtKEdrElY',
    appId: '1:157134124123:ios:a1399abcbd9e6526aefb7e',
    messagingSenderId: '157134124123',
    projectId: 'myinvoicemate',
    storageBucket: 'myinvoicemate.firebasestorage.app',
    iosBundleId: 'com.example.myinvoicemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0IJ5B5tOuFpj2RmxyRtbaGDHtKEdrElY',
    appId: '1:157134124123:ios:a1399abcbd9e6526aefb7e',
    messagingSenderId: '157134124123',
    projectId: 'myinvoicemate',
    storageBucket: 'myinvoicemate.firebasestorage.app',
    iosBundleId: 'com.example.myinvoicemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzCsX1bbSX4KCBeERTzzQtLiMkAmkm9dQ',
    appId: '1:157134124123:web:074877d6e2aad879aefb7e',
    messagingSenderId: '157134124123',
    projectId: 'myinvoicemate',
    authDomain: 'myinvoicemate.firebaseapp.com',
    storageBucket: 'myinvoicemate.firebasestorage.app',
    measurementId: 'G-7NZK67ZBLF',
  );
}
